version: "3"
services:
  web:
    build: .
    ports:
      - "6200:5000"
    volumes:
      - ./:/home/arsene/USSD/app
    depends_on:
      - db
  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432
