version: "3"
services:
  web:
    build: .
    ports:
      - "6200:5000"
    volumes:
      - ./:/home/app/
    depends_on:
      - db
  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "888:888"
    volumes:
      - /www/static
    depends_on:
      - web
